### ISSUE TITLE
Compatibility with Python < 3.9

### ISSUE THREAD

**Issue by Nemecsek** [Mortafix/magiclit#1]
It would be better not to use the new Python3.9 syntax for `dict()` unions to be compatible with older Python3 versions. 
It is used in 4 points only in the whole project: 

Python3.9: `dictC = dictA | dictB` => Python3.8: `dictC = {**dictA, **dictB}`
Python3.9: `dictC |= dictA` => Python3.8: `dictC = {**dictC, **dictA}`

**Comment by Mortafix** [comment]
Used the classic **union operation** for every dict to increase compatibility with lower Python version
